
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ENTER = 30;
  public static final int OTHERWISE = 31;
  public static final int THAT = 12;
  public static final int STRING_LITERAL = 22;
  public static final int TEXTFIELD = 11;
  public static final int STEPLITERAL = 8;
  public static final int WITH = 21;
  public static final int THERE = 34;
  public static final int WEBPAGE = 10;
  public static final int INTEGER = 7;
  public static final int TIME = 17;
  public static final int SHOULD = 23;
  public static final int HAVE = 13;
  public static final int MINUS = 42;
  public static final int PREDEFINED = 45;
  public static final int IS = 32;
  public static final int PLUS = 41;
  public static final int EXIT = 35;
  public static final int MAIN = 2;
  public static final int IF = 26;
  public static final int LOCALITYINDIC = 14;
  public static final int ID = 5;
  public static final int REFRESH = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RESULTACTION = 18;
  public static final int PIPE = 6;
  public static final int NEWLINE = 4;
  public static final int EXISTS = 33;
  public static final int NUMBER = 39;
  public static final int URL = 19;
  public static final int POSITIONINDIC = 15;
  public static final int URL_LITERAL = 44;
  public static final int FROM = 40;
  public static final int INTO = 29;
  public static final int COLON = 3;
  public static final int BE = 43;
  public static final int CLICK = 36;
  public static final int TO = 28;
  public static final int VALUE = 24;
  public static final int TEXT = 38;
  public static final int CONTAIN = 16;
  public static final int ATTRIBUTE = 20;
  public static final int BUTTON = 9;
  public static final int DO = 25;
  public static final int GO = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "COLON",
  "NEWLINE",
  "ID",
  "PIPE",
  "INTEGER",
  "STEPLITERAL",
  "BUTTON",
  "WEBPAGE",
  "TEXTFIELD",
  "THAT",
  "HAVE",
  "LOCALITYINDIC",
  "POSITIONINDIC",
  "CONTAIN",
  "TIME",
  "RESULTACTION",
  "URL",
  "ATTRIBUTE",
  "WITH",
  "STRING_LITERAL",
  "SHOULD",
  "VALUE",
  "DO",
  "IF",
  "GO",
  "TO",
  "INTO",
  "ENTER",
  "OTHERWISE",
  "IS",
  "EXISTS",
  "THERE",
  "EXIT",
  "CLICK",
  "REFRESH",
  "TEXT",
  "NUMBER",
  "FROM",
  "PLUS",
  "MINUS",
  "BE",
  "URL_LITERAL",
  "PREDEFINED"
  };
}

